### ISSUE TITLE
[REFACTOR] 메인 액티비티 내 프래그먼트 전환

### ISSUE THREAD

**Issue by eshc123** [woowa-techcamp-2022/android-repo-06#32]
해당 탭을 select할 때마다 fragment가 생성되고 replace되어 개선이 필요함

**Comment by eshc123** [comment]
화면 회전 시 문제가 발생할 수 있다고 하여 일단 이슈 열고 있는 상태로 조금 더 고민해보겠습니다. backStack의 태그를 사용하는게 좋겠다고 하시더라구요. 다른 중요 이슈 해결 후 수정 작업해보도록 하겠습니다.

**Comment by Skipancho** [comment]
Ivy님이 소개해주신 Fragment KTX를 공부해보고 적용하면 어떨까 생각해봅니다 ㅎㅎ

**Comment by eshc123** [comment]
show& hide 적용
